server:
  port: 8081

spring:
  application:
    name: Identity-Microservice
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:mysql://${IDENTITY_DB_HOST:identity-mysql}:${IDENTITY_DB_PORT:3306}/${IDENTITY_DB_NAME:identity_db}
    username: ${IDENTITY_DB_USERNAME:identity_user}
    password: ${IDENTITY_DB_PASSWORD:identity_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
#  h2:
#    console:
#      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration

eureka:
  client:
    service-url:
#      defaultZone: http://host.docker.internal:8761/eureka/
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}